### ISSUE TITLE
supply config file to "make run" command 

### ISSUE THREAD

**Issue by SpheMakh** [SpheMakh/HI-Inator#1]
The configuration should be passed when running the simulator. Something like this

```
make run config=config_file.json
```

Also  need to rename `parameters.json` to `example_config.json`, then the user should not modify this file but make a copy which they can customise and pass to the simulator via `make run`

**Comment by sphemakh** [comment]
Fixed in 692fdb886b8e8feed08f8733c8687b568cd3c075
