### ISSUE TITLE
make run not working on exemple file

### ISSUE THREAD

**Issue by chiaraf** [SpheMakh/HI-Inator#5]
Hi @SpheMakh. I get the following error message running make run on your exemple image:

2015/06/15 09:01:23 INFO: ## Mon Jun 15 09:01:23 2015:
/code/depends/pyxis/Pyxis/bin/pyxis CFG=//input/parameters.json DESTDIR=//output OUTDIR=//output azishe
2015/06/15 09:01:23 PYXIS: running command azishe
Traceback (most recent call last):
  File "/code/depends/pyxis/Pyxis/bin/pyxis", line 281, in <module>
    Pyxis.Internals.run(_commands);
  File "/code/depends/pyxis/Pyxis/Internals.py", line 1099, in run
    comcall();
  File "./pyxis-hikat.py", line 146, in azishe
    ncores(nm)
  File "./pyxis-hikat.conf", line 11, in ncores
    n = int(0.6_(psutil.NUM_CPUS - psutil.cpu_percent()/100*psutil.NUM_CPUS))
AttributeError: 'module' object has no attribute 'NUM_CPUS'
2015/06/15 09:01:23 ERROR: Exception raised, aborting

**Comment by sphemakh** [comment]
I see the error: I'm fixing it now.

**Comment by sphemakh** [comment]
The `psutil` in the container was different from the one on my machine. Update the repo, and all should be well.

**Comment by chiaraf** [comment]
I have run:

cd HI-Inator
git pull origin master
make force-build 
make run

And I get the following errors:

2015/06/15 10:39:08 PYXIS: per(MS_LSM,make_and_sim,persist=0): iterating over MS_LSM=//output/example_sim-0000.MS,example_sim-0000.fits //output/example_sim-0001.MS,example_sim-0001.fits
2015/06/15 10:39:08 PYXIS: splitting into 2 jobs, up to 1 MS_LSM's per job, staggered by 10s
2015/06/15 10:39:18 PYXIS: 2 jobs launched, waiting for finish
2015/06/15 10:39:18 ERROR: job #0 (MS_LSM=//output/example_sim-0000.MS,example_sim-0000.fits) exited with error status 1, waiting for 1 more jobs to complete
2015/06/15 10:39:18 ERROR: job #1 (MS_LSM=//output/example_sim-0001.MS,example_sim-0001.fits) exited with error status 1, waiting for 0 more jobs to complete
2015/06/15 10:39:18 ABORT: 2 of 2 jobs have failed
2015/06/15 10:39:18 ERROR: exiting with error code 1, check the logs for errors
2015/06/15 10:39:18 INFO: last logfile was //output/log-hisims.txt

In the log file:

...

2015/06/15 10:39:08 [0] WARNING: Error accessing //output/example_sim-0000.MS
Traceback (most recent call last):
  File "/code/depends/pyxis/Pyxides/ms.py", line 470, in _msddid_accessed_Template
    ddtab = ms(subtable="DATA_DESCRIPTION");
  File "/code/depends/pyxis/Pyxides/ms.py", line 66, in ms
    msname = table(msname,ack=False).getkeyword(subtable);
 File "/usr/lib/python2.7/dist-packages/pyrap/tables/table.py", line 319, in __init__
    Table.**init** (self, tabname, lockopt, opt);
RuntimeError: Table //output/example_sim-0000.MS does not exist
2015/06/15 10:39:08 [0] INFO: You image is now LWIMAGER approved ;) 
Traceback (most recent call last):
  File "/code/depends/pyxis/Pyxis/Commands.py", line 303, in _per
    Pyxis.Internals.run(_commands);
  File "/code/depends/pyxis/Pyxis/Internals.py", line 1099, in run
    comcall();
  File "./pyxis-hikat.py", line 189, in make_and_sim
    simsky(addnoise=addnoise, scalenoise=scalenoise, *_options)
  File "./pyxis-hikat.py", line 53, in simsky
    ms.set_default_spectral_info()
  File "/code/depends/pyxis/Pyxides/ms.py", line 522, in set_default_spectral_info
    tab = ms(subtable='SPECTRAL_WINDOW')
  File "/code/depends/pyxis/Pyxides/ms.py", line 66, in ms
    msname = table(msname,ack=False).getkeyword(subtable);
  File "/usr/lib/python2.7/dist-packages/pyrap/tables/table.py", line 319, in __init__
    Table.**init** (self, tabname, lockopt, opt);
RuntimeError: Table //output/example_sim-0000.MS does not exist
2015/06/15 10:39:08 [0] ERROR: per-loop failed for //output/example_sim-0000.MS,example_sim-0000.fits
2015/06/15 10:39:18 PYXIS: 2 jobs launched, waiting for finish
2015/06/15 10:39:18 [1] PYXIS: started job 1 for //output/example_sim-0001.MS,example_sim-0001.fits
2015/06/15 10:39:18 ERROR: job #0 (MS_LSM=//output/example_sim-0000.MS,example_sim-0000.fits) exited with error status 1, waiting for 1 more jobs to complete
2015/06/15 10:39:18 [1] PYXIS: per-loop, setting MS_LSM=//output/example_sim-0001.MS,example_sim-0001.fits
2015/06/15 10:39:18 [1] PYXIS: running command make_and_sim
2015/06/15 10:39:18 [1] WARNING: Error accessing //output/example_sim-0001.MS
...
